### ISSUE TITLE
no such table: BackingPhotoTable

### ISSUE THREAD

**Issue by jesjimher** [masneyb/shotwell-site-generator#1]
Hi!

I'm trying to use this tool, looks very promising, but after all night generating thumbnails, I'm stuck at the following error:

```
Traceback (most recent call last):
  File "./shotwell_site_generator.py", line 110, in <module>
    process_photos(ARGPARSER.parse_args(sys.argv[1:]))
  File "./shotwell_site_generator.py", line 49, in process_photos
    all_media = fetcher.get_all_media(rating)
  File "/home/jesus/git/shotwell-site-generator/media_fetcher.py", line 45, in get_all_media
    self.__fetch_media(all_media, min_rating)
  File "/home/jesus/git/shotwell-site-generator/media_fetcher.py", line 130, in __fetch_media
    for row in cursor.execute(qry, str(min_rating)):
sqlite3.OperationalError: no such table: BackingPhotoTable
```

During thumbnail generation I got some errors due to broken JPGs, but I don't know how to fix this.

Any idea?

**Comment by masneyb** [comment]
What version of shotwell are you using? That table is used for the RAW photos.

For the time being, you can work around this by editing media_fetcher.py, go around line 119 in __fetch_media() and comment out with a # (or remove) the following chunk of code:

        # Now download RAW photos...
        qry = "SELECT PhotoTable.event_id, PhotoTable.id, " + \
              "PhotoTable.filename as download_filename, " + \
              "BackingPhotoTable.filepath AS filename, PhotoTable.title, PhotoTable.comment, " + \
              "PhotoTable.filesize, PhotoTable.exposure_time, PhotoTable.rating, " + \
              "PhotoTable.width, PhotoTable.height, PhotoTable.orientation " + \
              "FROM PhotoTable, BackingPhotoTable " + \
              "WHERE PhotoTable.rating >= ? AND PhotoTable.develop_embedded_id != -1 AND " + \
              "BackingPhotoTable.id=PhotoTable.develop_embedded_id " + \
              "ORDER BY PhotoTable.exposure_time"
        cursor = self.conn.cursor()
        for row in cursor.execute(qry, str(min_rating)):
            self.__process_photo_row(all_media, row, row["download_filename"], True)

The thumbnails that were already generated will be cached so it won't take all night again to regenerate the thumbnails.

**Comment by jesjimher** [comment]
I'm using 0.30.7. Perhaps the problem is I don't have any RAW photo, and that's why this table doesn't exist. 

I'll try commenting those lines, it looks like it should fix the issue. Perhaps code could check if table exists before proceeding? It looks like Shotwell creates tables on demand, so I guess somebody who doesn't use Shotwell for videos could face the same problem.

Thanks a lot!

**Comment by masneyb** [comment]
OK, I'll change it to skip that query if the table doesn't exist. I'll also make the same change for the video table.

I'd appreciate any feedback that you have about the generated site once you get it working.
