### ISSUE TITLE
Ignoring event id -1 with no media

### ISSUE THREAD

**Issue by jesjimher** [masneyb/shotwell-site-generator#2]
Hi

I'm trying to generate HTML from my Shotwell DB, I've encountered another error:

```
...
2020-05-25 16:40:11,339 Generating thumbnail /compartido/webshotwell/thumbnails/event/2c/3023.png
2020-05-25 16:40:16,048 Ignoring event id -1 with no media.
Traceback (most recent call last):
  File "./shotwell_site_generator.py", line 113, in <module>
    process_photos(ARGPARSER.parse_args(sys.argv[1:]))
  File "./shotwell_site_generator.py", line 49, in process_photos
    all_media = fetcher.get_all_media(rating)
  File "/home/jesus/git/shotwell-site-generator/media_fetcher.py", line 76, in get_all_media
    self.__fetch_tags(all_media)
  File "/home/jesus/git/shotwell-site-generator/media_fetcher.py", line 227, in __fetch_tags
    all_media["events_by_year"][media["year"]]["tags"].append(row["id"])
KeyError: '1970'
```

Any clue about what might be the problem? It seems it's looking for an event called '1970', but I have no such event...

**Comment by jesjimher** [comment]
I have looked a little bit more into the issue, and I think the issue subject message has nothing to do with the problem, sorry about that...

What I've seen is that error is about some media from year 1970 missing. Which is right, because, running Shotwell, I don't have any media from this year. But debugging a little bit more, I've found that the actual file which is causing the error is a video that was imported from a camera with a bad date/no date at all, and thus was imported into the 1970 folder. Then, after importing it, I corrected date to the real date (2011) using Shotwell options, but file stayed at 1970 folder (Shotwell doesn't move file once imported, no matter if date is changed). Looking at VideoTable I see the right date at timestamp column, so I don't exactly know what's happening here. 

Is it possible that your script gets media date from file exif information instead of Shotwell database? Normally they would be both in sync, but since the problematic file is a video, it has no EXIF information by itself. Or perhaps date is recovered from file path, which doesn't correspond to actual date?

Hope it helps, I really would like it to work, since having an HTML version of Shotwell database is a fantastic idea :-)

**Comment by masneyb** [comment]
I just pushed up a commit that should fix the issue for you. In your shotwell library, look to see if any of your media is in the "No Event" category (below all of the years) and make sure to put a timestamp with all of them. I haven't fully tested the HTML generation with the no events category.

The program doesn't read the timestamps from the photos (via EXIF) or the videos; it only reads from the database.
